"""
文件生成器 — Jinja2 模板渲染 → 写出 SKILL 目录
"""
from pathlib import Path
import json
import os
import jinja2

from core.state import SkillSpec, LorebookEntry, LorebookStrategy, InsertPosition

TEMPLATE_DIR = Path(__file__).parent / "templates"


def generate(spec: SkillSpec, output_dir: Path):
    """渲染所有模板并写入输出目录"""
    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(TEMPLATE_DIR)),
        trim_blocks=True, lstrip_blocks=True,
    )
    
    output_dir = Path(output_dir)
    
    # 目录
    (output_dir / "skill").mkdir(parents=True, exist_ok=True)
    (output_dir / "tools").mkdir(parents=True, exist_ok=True)
    (output_dir / "saves").mkdir(parents=True, exist_ok=True)
    
    # SKILL.md（给人读的入口）
    _render(env, "SKILL.md.j2", output_dir / "SKILL.md", spec=spec)
    
    # AGENTS.md（硬禁令）
    _render(env, "AGENTS.md.j2", output_dir / "AGENTS.md", spec=spec)
    
    # loop_schema.json（给引擎读）
    schema_json = spec.to_json()
    (output_dir / "loop_schema.json").write_text(
        json.dumps(schema_json, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    
    # lorebook.json
    lorebook_data = {
        "entries": [e.to_dict() for e in spec.lorebook_entries],
        "generated_at": spec.generated_at,
    }
    (output_dir / "lorebook.json").write_text(
        json.dumps(lorebook_data, ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    
    # game_config.json（默认配置）
    _render(env, "game_config.json.j2", output_dir / "game_config.json", spec=spec)
    
    # 参考文件
    for ref in spec.reference_files:
        filepath = output_dir / "skill" / ref["filename"]
        _render(env, "reference_section.md.j2", filepath, ref=ref)
    
    # 工具脚本
    for tool in spec.tools:
        filename = tool['filename']
        filepath = output_dir / "tools" / filename
        template_name = f"{filename}.j2"
        if (TEMPLATE_DIR / template_name).exists():
            try:
                _render(env, template_name, filepath, spec=spec, tool=tool)
            except Exception:
                _write_fallback_tool(filepath)
        else:
            # 无匹配模板 → 生成通用 roller
            _write_generic_tool(filepath, tool)
    
    # session_starter.py 和 state_cli.py 必须存在
    _render(env, "session_starter.py.j2", output_dir / "tools" / "session_starter.py", spec=spec)
    _render(env, "state_cli.py.j2", output_dir / "tools" / "state_cli.py", spec=spec)

    # 从 Lorebook 条目自动填充空数据池
    _auto_fill_data_pools(spec, output_dir)


def _render(env, template_name, output_path, **kwargs):
    try:
        template = env.get_template(template_name)
        content = template.render(**kwargs)
        output_path.write_text(content, encoding="utf-8")
    except jinja2.TemplateNotFound:
        if not output_path.exists():
            output_path.write_text("# Generated by TRPG-to-SKILL\n", encoding="utf-8")
    except Exception as e:
        print(f"    ⚠ 模板渲染失败: {template_name} - {e}")


def _write_fallback_tool(filepath):
    filepath.write_text(
        '"""TRPG-to-SKILL fallback tool."""\n'
        'import sys, json\n'
        'def main():\n'
        '    if hasattr(sys.stdout, "reconfigure"):\n'
        '        sys.stdout.reconfigure(encoding="utf-8")\n'
        '    print(json.dumps({"ok": True, "source": "fallback"}, ensure_ascii=False))\n'
        'if __name__ == "__main__": main()\n',
        encoding="utf-8"
    )


def _write_generic_tool(filepath, tool):
    """为没有预置模板的工具生成通用 roller"""
    import json as _json
    data_pool = tool.get("data_pools", [])
    pool_json = _json.dumps(data_pool, ensure_ascii=False, indent=4)
    code = f'''"""
{tool.get("filename", "tool.py")} — {tool.get("type", "通用工具")}

用法:
    python tools/{tool.get("filename", "tool.py")} --random
"""
import sys
import json
import random

_rng = random.SystemRandom()

POOL = {pool_json}

def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    result = _rng.choice(POOL) if POOL else {{"ok": True}}
    print(json.dumps(result, ensure_ascii=False))

if __name__ == "__main__":
    main()
'''
    filepath.write_text(code, encoding="utf-8")


def _auto_fill_data_pools(spec: SkillSpec, output_dir: Path):
    """从 Lorebook 条目自动填充工具的空数据池"""
    item_entries = [e for e in spec.lorebook_entries if e.type == 'item']
    npc_entries = [e for e in spec.lorebook_entries if e.type == 'npc']

    for tool in spec.tools:
        if tool.get("data_pools") and len(tool["data_pools"]) > 0:
            continue  # 已有数据，跳过

        filename = tool['filename']
        filepath = output_dir / "tools" / filename
        pool = []

        if 'candy' in filename or 'item' in filename:
            for e in item_entries:
                content = e.content
                effect = ''
                desc = content
                for sep in ['效果:', '效果：', 'Effect:', 'effect:']:
                    if sep in content:
                        parts = content.split(sep, 1)
                        desc = parts[0].rstrip('.。 ')
                        effect = parts[1].rstrip('.。 ') if len(parts) > 1 else ''
                        break
                pool.append({
                    'name': e.title,
                    'description': desc[:120],
                    'effect': effect[:120]
                })
        elif 'npc' in filename:
            for e in npc_entries:
                pool.append({
                    'name': e.title,
                    'description': e.content[:200]
                })

        if pool and filepath.exists():
            _write_generic_tool(filepath, {"filename": filename, "data_pools": pool})

    # 自动创建物品索引 Lorebook 条目（关键词触发，供 LLM 查列表）
    if len(item_entries) >= 2:
        index_lines = []
        index_keys = set()
        for e in item_entries[:60]:
            idx = e.title[:30]
            desc = e.content[:60].replace('\n', ' ')
            index_lines.append(f"{idx}: {desc}")
            # 从标题和内容中提取关键词
            for word in ['糖','果','物','品','买','卖','支','付','草莓','葡萄','薄荷','巧克力',
                         '牛奶','柠檬','橙','苹果','蜜','花','茶','粉','蓝','红','绿','黄','白','黑']:
                if word in idx or word in (e.content[:40]):
                    index_keys.add(word)
        if index_lines:
            index_entry = LorebookEntry(
                id="item_index",
                title="可用物品索引",
                content="\n".join(index_lines),
                type="summary",
                keys=list(index_keys)[:15],
                strategy=LorebookStrategy.NORMAL,
                position=InsertPosition.AFTER_INSTRUCTION,
                scan_depth=10,
                priority=40,
                recursive=False,
                is_dynamic=False
            )
            spec.lorebook_entries.append(index_entry)
            # 重写 lorebook.json
            lorebook_data = {
                "entries": [e.to_dict() for e in spec.lorebook_entries],
                "generated_at": spec.generated_at,
            }
            (output_dir / "lorebook.json").write_text(
                json.dumps(lorebook_data, ensure_ascii=False, indent=2),
                encoding="utf-8"
            )

    # 自动生成 Agent 工具定义
    _build_agent_tools(spec, output_dir, item_entries, npc_entries)


def _build_agent_tools(spec: SkillSpec, output_dir: Path,
                       item_entries: list, npc_entries: list):
    """根据 Lorebook 条目自动生成 Agent 工具定义，写入 loop_schema.json"""
    tools = []

    if len(item_entries) >= 2:
        item_names = [e.title for e in item_entries[:30]]
        types = list(set(
            (e.content[:30] or e.title[:10])
            for e in item_entries[:20]
        ))[:8]
        tools.append({"type": "function", "function": {
            "name": "list_items",
            "description": f"列出可用物品。已知物品: {', '.join(item_names[:20])}。共{len(item_entries)}个。用于需要展示选项时查询。",
            "parameters": {
                "type": "object",
                "properties": {
                    "type": {"type": "string", "description": f"物品类型过滤 (可选, 可选值: {', '.join(types[:5])})"},
                    "keyword": {"type": "string", "description": "关键词搜索 (可选)"}
                },
                "required": []
            }
        }})
        tools.append({"type": "function", "function": {
            "name": "get_item",
            "description": "获取指定物品的详细描述。已知物品: " + ", ".join(item_names[:15]),
            "parameters": {
                "type": "object",
                "properties": {
                    "name": {"type": "string", "description": "物品名称"}
                },
                "required": ["name"]
            }
        }})

    if len(npc_entries) >= 2:
        npc_names = [e.title for e in npc_entries[:20]]
        tools.append({"type": "function", "function": {
            "name": "list_npcs",
            "description": f"列出已知NPC。已知: {', '.join(npc_names[:15])}。共{len(npc_entries)}个。",
            "parameters": {"type": "object", "properties": {}, "required": []}
        }})
        tools.append({"type": "function", "function": {
            "name": "query_lorebook",
            "description": "查询 Lorebook 中的角色、物品、地点或规则信息。",
            "parameters": {
                "type": "object",
                "properties": {
                    "type": {"type": "string", "enum": ["npc", "item", "location", "rule"], "description": "实体类型"},
                    "keyword": {"type": "string", "description": "关键词"}
                },
                "required": ["type"]
            }
        }})

    if tools:
        # 更新 SkillSpec 的 phase_scripts... 实际上需要更新 loop_schema.json
        try:
            schema_path = output_dir / "loop_schema.json"
            if schema_path.exists():
                data = json.loads(schema_path.read_text(encoding="utf-8"))
                data["agent_tools"] = tools
                schema_path.write_text(
                    json.dumps(data, ensure_ascii=False, indent=2),
                    encoding="utf-8"
                )
        except Exception:
            pass
